-- Removes everything demo_setup.sql created.
WHENEVER SQLERROR CONTINUE
DROP TABLE QUACK_DEMO_DEPARTMENTS PURGE;
DROP TABLE QUACK_DEMO_LOG PURGE;
DROP TABLE QUACK_DEMO_TYPES PURGE;
DROP FUNCTION QUACK_DEMO_ADD;
DROP PROCEDURE QUACK_DEMO_GREET;
DROP PROCEDURE QUACK_DEMO_LIST;
EXIT
