-- oracle_scanner demo schema.
--
-- Creates the objects the README's "Try it yourself" section and the examples
-- in duckdb_functions() use. Safe to run more than once: existing demo tables
-- are dropped first and the PL/SQL objects are replaced. Works on Oracle 19c,
-- 23ai Free and OCI Autonomous, in whatever schema you connect as.
--
--   sqlplus user/password@host:1521/service @demo_setup.sql

SET SERVEROUTPUT ON
WHENEVER SQLERROR CONTINUE

BEGIN
    FOR victim IN (SELECT table_name FROM user_tables
                   WHERE table_name IN ('QUACK_DEMO_DEPARTMENTS', 'QUACK_DEMO_LOG', 'QUACK_DEMO_TYPES'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || victim.table_name || ' PURGE';
    END LOOP;
END;
/

-- A small table to scan, filter and read in parallel. The key is NUMBER with
-- whole values, which is what oracle_scan_parallel requires.
CREATE TABLE QUACK_DEMO_DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(6)    NOT NULL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(40) NOT NULL,
    LOCATION        VARCHAR2(40),
    HEADCOUNT       NUMBER(6)
);

INSERT INTO QUACK_DEMO_DEPARTMENTS VALUES (10, 'ACCOUNTING', 'NEW YORK', 12);
INSERT INTO QUACK_DEMO_DEPARTMENTS VALUES (20, 'RESEARCH',   'DALLAS',   38);
INSERT INTO QUACK_DEMO_DEPARTMENTS VALUES (30, 'SALES',      'CHICAGO',  57);
INSERT INTO QUACK_DEMO_DEPARTMENTS VALUES (40, 'OPERATIONS', NULL,     NULL);

-- A table to write to. IDENTITY and DEFAULT are here on purpose: they are what
-- INSERT ... RETURNING and the "columns you do not name" rule demonstrate.
CREATE TABLE QUACK_DEMO_LOG (
    LOG_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    LABEL    VARCHAR2(50),
    AMOUNT   NUMBER(10,2),
    LOGGED_AT DATE DEFAULT SYSDATE
);

-- One row carrying one column of every type the type table in the README maps.
CREATE TABLE QUACK_DEMO_TYPES (
    N_INT       NUMBER(5,0),
    N_DECIMAL   NUMBER(10,5),
    N_ANY       NUMBER,
    V           VARCHAR2(20),
    C           CHAR(10),
    D           DATE,
    TS          TIMESTAMP(6),
    TS_NS       TIMESTAMP(9),
    TS_TZ       TIMESTAMP(6) WITH TIME ZONE,
    R           RAW(16),
    BF          BINARY_FLOAT,
    BD          BINARY_DOUBLE,
    N_NULL      NUMBER
);

INSERT INTO QUACK_DEMO_TYPES VALUES (
    42, 3.14159, 1/3, 'text', 'padded',
    DATE '2024-03-01',
    TIMESTAMP '2024-03-01 12:34:56.123456',
    TIMESTAMP '2024-03-01 12:34:56.123456789',
    TIMESTAMP '2024-03-01 12:34:56.123456 +02:00',
    UTL_RAW.CAST_TO_RAW('abc'),
    1.5, 1.5, NULL);

COMMIT;

-- A function, an OUT procedure and a REF CURSOR procedure, for oracle_arguments
-- and the oracle_call_* family.
CREATE OR REPLACE FUNCTION QUACK_DEMO_ADD(P_A NUMBER, P_B NUMBER) RETURN NUMBER IS
BEGIN
    RETURN P_A + P_B;
END;
/

CREATE OR REPLACE PROCEDURE QUACK_DEMO_GREET(P_NAME IN VARCHAR2, P_GREETING OUT VARCHAR2) IS
BEGIN
    P_GREETING := 'hello, ' || P_NAME;
END;
/

CREATE OR REPLACE PROCEDURE QUACK_DEMO_LIST(P_ROWS OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_ROWS FOR SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM QUACK_DEMO_DEPARTMENTS ORDER BY DEPARTMENT_ID;
END;
/

-- One small object per call shape the oracle_call_* family has, so every
-- function's documented example has something of exactly that shape to call.
-- TODO(live): these six have not yet been run against a live Oracle; only their
-- argument shapes are checked, offline, by TestFunctionExamplesRun in
-- test/cpp/adapter_test.cpp. Run demo_setup.sql and every duckdb_functions()
-- example against 19c and 23ai before calling them verified.

-- oracle_call_number: a function with no arguments returning NUMBER.
CREATE OR REPLACE FUNCTION QUACK_DEMO_ANSWER RETURN NUMBER IS
BEGIN
    RETURN 42;
END;
/

-- oracle_call_out_number: a procedure whose only argument is a NUMBER OUT.
CREATE OR REPLACE PROCEDURE QUACK_DEMO_COUNT_DEPARTMENTS(P_COUNT OUT NUMBER) IS
BEGIN
    SELECT COUNT(*) INTO P_COUNT FROM QUACK_DEMO_DEPARTMENTS;
END;
/

-- oracle_call_out_varchar: a procedure whose only argument is a VARCHAR2 OUT.
CREATE OR REPLACE PROCEDURE QUACK_DEMO_MOTTO(P_TEXT OUT VARCHAR2) IS
BEGIN
    P_TEXT := 'no Oracle client required';
END;
/

-- oracle_call_inout_number: a procedure whose only argument is a NUMBER IN OUT.
CREATE OR REPLACE PROCEDURE QUACK_DEMO_DOUBLE(P_VALUE IN OUT NUMBER) IS
BEGIN
    P_VALUE := P_VALUE * 2;
END;
/

-- oracle_call_inout_varchar: a procedure whose only argument is a VARCHAR2 IN OUT.
CREATE OR REPLACE PROCEDURE QUACK_DEMO_SHOUT(P_TEXT IN OUT VARCHAR2) IS
BEGIN
    P_TEXT := UPPER(P_TEXT);
END;
/

-- oracle_call_implicit: a procedure with no arguments returning an implicit
-- result set (Oracle 12c and later).
CREATE OR REPLACE PROCEDURE QUACK_DEMO_IMPLICIT IS
    departments SYS_REFCURSOR;
BEGIN
    OPEN departments FOR SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM QUACK_DEMO_DEPARTMENTS ORDER BY DEPARTMENT_ID;
    DBMS_SQL.RETURN_RESULT(departments);
END;
/

SELECT object_name, object_type, status
FROM user_objects WHERE object_name LIKE 'QUACK_DEMO%' ORDER BY object_name;

EXIT
